"""Change media storage from binary to URL

Revision ID: 483f63375ab8
Revises: 57cfcdb2d1cc
Create Date: 2025-09-04 12:13:27.087701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '483f63375ab8'
down_revision: Union[str, Sequence[str], None] = '57cfcdb2d1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add the new file_url column, but allow it to be NULL temporarily.
    op.add_column('media', sa.Column('file_url', sa.String(length=1024), nullable=True))
    
    # Step 2: Update all existing rows to have a placeholder value in the new column.
    op.execute("UPDATE media SET file_url = 'NEEDS_MIGRATING' WHERE file_url IS NULL")
    
    # Step 3: Now that no rows are NULL, change the column to be NOT NULL.
    op.alter_column('media', 'file_url', nullable=False)
    
    # Step 4: Drop the old, unused file_data column.
    op.drop_column('media', 'file_data')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # This reverses the process: add the old column back, then drop the new one.
    op.add_column('media', sa.Column('file_data', sa.LARGEBINARY(), autoincrement=False, nullable=True))
    op.drop_column('media', 'file_url')
    
    # ### end Alembic commands ###