"""Initial migration

Revision ID: 9d3a77f0f3b6
Revises: 
Create Date: 2025-09-04 10:46:42.426531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3a77f0f3b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('media', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('posts', sa.Column('media_id', sa.Integer(), nullable=True))
    op.alter_column('posts', 'content_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'clean',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'body',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'posts', 'media', ['media_id'], ['id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('posts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'clean',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'content_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('posts', 'media_id')
    op.alter_column('media', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
